### ISSUE TITLE
`set-output` is deprecated

### ISSUE THREAD

**Issue by dgw** [limitusus/json-syntax-check#14]
This `set-output` line will cause the action to fail with an error as of June 1, 2023 ([per GitHub blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)):

https://github.com/limitusus/json-syntax-check/blob/2505a77aa5181d0d0f5b94cf5aaaf3abb07a2cb5/json_syntax_check#L13

It presently generates a warning, as of Actions Runner version 2.298.2:

![image](https://user-images.githubusercontent.com/164140/196862329-b9ec42e1-c02b-47e5-a4f2-ca6c85015866.png)

**Comment by dgw** [comment]
Super fast response, thank you!

Since you've bumped the action to v2.0.0 with this and a few other changes, can you make a `v2` tag like the `v1` one that always points to the latest version in that series?

**Comment by limitusus** [comment]
Sure I've just pushed `v2` tag pointing `v2.0.0` currently.

**Comment by dgw** [comment]
Thank you again!
