### ISSUE TITLE
Support for file/directory exclusion

### ISSUE THREAD

**Issue by ciscorucinski** [limitusus/json-syntax-check#24]
Is there support for exclusion criteria; such as for files or directories?

**Comment by ciscorucinski** [comment]
I should add that the files I want to exclude are JSON streams such as ndjson, jsonl, or concatenated JSON. These will cause a failure with this Action, as they match the pattern

```javascript
{
    // valid JSON object 1
}
{
    // valid JSON object 2
}
```

**Comment by limitusus** [comment]
Currently there is no mechanism to specify exclusion rule, but it should be possible to exclude targets with the proper writing of regexp.

**Comment by ciscorucinski** [comment]
Thanks for the reply. I will look into the regex pattern to exclude files.

Just as a fyi, Ruby's Yajl, seems to be a drop in replacement for JSON that also handles JSON streams if you ever want to extend the JSON functionality.

https://github.com/brianmario/yajl-ruby
